/***********************************************************************************************//**
 * \file xensiv_pas_gas_r290_regs.h
 *
 * Description: This file contains the register definitions
 *              for interacting with the XENSIV™ PAS R290 GAS sensor.
 *
 ***************************************************************************************************
 * \copyright
 * Copyright 2025-2026 Infineon Technologies AG
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 **************************************************************************************************/

#ifndef XENSIV_PAS_GAS_R290_REGS_H_
#define XENSIV_PAS_GAS_R290_REGS_H_

// ------------------- R290 Sensor Only Registers ------------------//
#define XENSIV_PAS_GAS_R290_REG_DEV_ID            (0x23U)
#define XENSIV_PAS_GAS_R290_REG_ABOC_PREFILL      (0x5DU)
#define XENSIV_PAS_GAS_R290_REG_ALARM_CFG         (0x5FU)
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST         (0x60U)
#define XENSIV_PAS_GAS_R290_REG_DENOISE_CFG       (0x61U)
#define XENSIV_PAS_GAS_R290_REG_ABOC_CYCLE        (0x62U)
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_CLR     (0x63U)

// -------------------  R290 Sensor Only Registers ------------------- //
// DEV_ID
#define XENSIV_PAS_GAS_R290_REG_DEV_ID_VAL_POS            (0U)
#define XENSIV_PAS_GAS_R290_REG_DEV_ID_VAL_MSK            (0xffU << XENSIV_PAS_GAS_R290_REG_DEV_ID_VAL_POS)
// ABOC_PREFILL
#define XENSIV_PAS_GAS_R290_REG_ABOC_PREFILL_VAL_POS      (0U)
#define XENSIV_PAS_GAS_R290_REG_ABOC_PREFILL_VAL_MSK      (0xffU << XENSIV_PAS_GAS_R290_REG_ABOC_PREFILL_VAL_POS)
// ALARM_CFG
#define XENSIV_PAS_GAS_R290_REG_ALARM_CFG_ALARM_POL_POS   (0U)
#define XENSIV_PAS_GAS_R290_REG_ALARM_CFG_ALARM_POL_MSK   (0x01U << XENSIV_PAS_GAS_R290_REG_ALARM_CFG_ALARM_POL_POS)
// SELF_TEST
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_VOLTAGE_ERR_POS     (0U)
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_VOLTAGE_ERR_MSK     (0x01U << XENSIV_PAS_GAS_R290_REG_SELF_TEST_VOLTAGE_ERR_POS)
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_TEMP_ERR_POS        (1U)
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_TEMP_ERR_MSK        (0x01U << XENSIV_PAS_GAS_R290_REG_SELF_TEST_TEMP_ERR_POS)
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_SIMIC_ERR_POS       (2U)
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_SIMIC_ERR_MSK       (0x01U << XENSIV_PAS_GAS_R290_REG_SELF_TEST_SIMIC_ERR_POS)
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_EMITTER_ERR_POS     (3U)
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_EMITTER_ERR_MSK     (0x01U << XENSIV_PAS_GAS_R290_REG_SELF_TEST_EMITTER_ERR_POS)
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_ABOC_DRIFT_ERR_POS  (4U)
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_ABOC_DRIFT_ERR_MSK  (0x01U << XENSIV_PAS_GAS_R290_REG_SELF_TEST_ABOC_DRIFT_ERR_POS)
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_LIFETIME_ERR_POS    (5U)
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_LIFETIME_ERR_MSK    (0x01U << XENSIV_PAS_GAS_R290_REG_SELF_TEST_LIFETIME_ERR_POS)
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_REPLACE_SEN_POS     (7U)
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_REPLACE_SEN_MSK     (0x01U << XENSIV_PAS_GAS_R290_REG_SELF_TEST_REPLACE_SEN_POS)
// DENOISE_CFG
#define XENSIV_PAS_GAS_R290_REG_DENOISE_CFG_SMOOTHING_FACT_POS    (0U)
#define XENSIV_PAS_GAS_R290_REG_DENOISE_CFG_SMOOTHING_FACT_MSK    (0x3fU << XENSIV_PAS_GAS_R290_REG_DENOISE_CFG_SMOOTHING_FACT_POS)
// ABOC_CYCLE
#define XENSIV_PAS_GAS_R290_REG_ABOC_CYCLE_SMOOTHING_FACT_POS     (0U)
#define XENSIV_PAS_GAS_R290_REG_ABOC_CYCLE_SMOOTHING_FACT_MSK     (0x3fU << XENSIV_PAS_GAS_R290_REG_ABOC_CYCLE_SMOOTHING_FACT_POS)
// SELF_TEST_CLR
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_CLR_VOLTAGE_ERR_CLR_POS     (0U)
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_CLR_VOLTAGE_ERR_CLR_MSK     (0x01U << XENSIV_PAS_GAS_R290_REG_SELF_TEST_CLR_VOLTAGE_ERR_CLR_POS)
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_CLR_TEMP_ERR_CLR_POS        (1U)
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_CLR_TEMP_ERR_CLR_MSK        (0x01U << XENSIV_PAS_GAS_R290_REG_SELF_TEST_CLR_TEMP_ERR_CLR_POS)
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_CLR_SIMIC_ERR_CLR_POS       (2U)
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_CLR_SIMIC_ERR_CLR_MSK       (0x01U << XENSIV_PAS_GAS_R290_REG_SELF_TEST_CLR_SIMIC_ERR_CLR_POS)
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_CLR_EMITTER_ERR_CLR_POS     (3U)
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_CLR_EMITTER_ERR_CLR_MSK     (0x01U << XENSIV_PAS_GAS_R290_REG_SELF_TEST_CLR_EMITTER_ERR_CLR_POS)
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_CLR_ABOC_DRIFT_ERR_CLR_POS  (4U)
#define XENSIV_PAS_GAS_R290_REG_SELF_TEST_CLR_ABOC_DRIFT_ERR_CLR_MSK  (0x01U << XENSIV_PAS_GAS_R290_REG_SELF_TEST_CLR_ABOC_DRIFT_ERR_CLR_POS)

#endif /* XENSIV_PAS_GAS_R290_REGS_H_ */
