/***********************************************************************************************//**
 * \file xensiv_pas_gas_a2l_regs.h
 *
 * Description: This file contains the register definitions
 *              for interacting with the XENSIV™ PAS A2L gas sensor.
 *
 ***************************************************************************************************
 * \copyright
 * Copyright 2025-2026 Infineon Technologies AG
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 **************************************************************************************************/

#ifndef XENSIV_PAS_GAS_A2L_REGS_H_
#define XENSIV_PAS_GAS_A2L_REGS_H_

#include "xensiv_pas_gas_regs.h"

// --------------------------A2L sensor Registers---------------------------//
#define XENSIV_PAS_GAS_A2L_REG_CFG_SAVE             (0x20U)
#define XENSIV_PAS_GAS_A2L_REG_DEV_ID_IDX           (0x22U)
#define XENSIV_PAS_GAS_A2L_REG_DEV_ID               (0x23U)
#define XENSIV_PAS_GAS_A2L_REG_ABOC_PREFILL         (0x5DU)
#define XENSIV_PAS_GAS_A2L_REG_GAS_CFG              (0x5EU)
#define XENSIV_PAS_GAS_A2L_REG_ALARM_CFG            (0x5FU)
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST            (0x60U)
#define XENSIV_PAS_GAS_A2L_REG_DENOISE_CFG          (0x61U)
#define XENSIV_PAS_GAS_A2L_REG_ABOC_CYCLE           (0x62U)
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_CLR        (0x63U)
#define XENSIV_PAS_GAS_A2L_REG_ALARM_HYS_H          (0x64U)
#define XENSIV_PAS_GAS_A2L_REG_ALARM_HYS_L          (0x65U)
#define XENSIV_PAS_GAS_A2L_REG_ABS_HUM_REF_H        (0x66U)
#define XENSIV_PAS_GAS_A2L_REG_ABS_HUM_REF_L        (0x67U)
#define XENSIV_PAS_GAS_A2L_REG_HC_CTRL              (0x68U)

// CFG_SAVE
#define XENSIV_PAS_GAS_A2L_REG_CFG_SAVE_VAL_POS         (0x3U)
#define XENSIV_PAS_GAS_A2L_REG_CFG_SAVE_VAL_MASK        (0x03U << XENSIV_PAS_GAS_A2L_REG_CFG_SAVE_VAL_POS)

// DEV_ID_IDX
#define XENSIV_PAS_GAS_A2L_REG_DEV_ID_IDX_POS          (0x0U)
#define XENSIV_PAS_GAS_A2L_REG_DEV_ID_IDX_MASK         (0xffU << XENSIV_PAS_GAS_A2L_REG_DEV_ID_IDX_POS)

// DEV_ID
#define XENSIV_PAS_GAS_A2L_REG_DEV_ID_VAL_POS            (0U)
#define XENSIV_PAS_GAS_A2L_REG_DEV_ID_VAL_MSK            (0xffU << XENSIV_PAS_GAS_A2L_REG_DEV_ID_VAL_POS)

// ABOC_PREFILL
#define XENSIV_PAS_GAS_A2L_REG_ABOC_PREFILL_VAL_POS      (0U)
#define XENSIV_PAS_GAS_A2L_REG_ABOC_PREFILL_VAL_MSK      (0xffU << XENSIV_PAS_GAS_A2L_REG_ABOC_PREFILL_VAL_POS)

// GAS_CFG
#define XENSIV_PAS_GAS_A2L_REG_GAS_CFG_GAS_SEL_POS      (0U)
#define XENSIV_PAS_GAS_A2L_REG_GAS_CFG_GAS_SEL_MASK     (0x03U << XENSIV_PAS_GAS_A2L_REG_GAS_CFG_GAS_SEL_POS)
#define XENSIV_PAS_GAS_A2L_REG_GAS_CFG_GAS_AVAIL_POS    (4U)
#define XENSIV_PAS_GAS_A2L_REG_GAS_CFG_GAS_AVAIL_MASK   (0x0FU << XENSIV_PAS_GAS_A2L_REG_GAS_CFG_GAS_AVAIL_POS)

// ALARM_CFG
#define XENSIV_PAS_GAS_A2L_REG_ALARM_CFG_ALARM_POL_POS   (0U)
#define XENSIV_PAS_GAS_A2L_REG_ALARM_CFG_ALARM_POL_MSK   (0x01U << XENSIV_PAS_GAS_A2L_REG_ALARM_CFG_ALARM_POL_POS)

// SELF_TEST
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_VOLTAGE_ERR_POS     (0U)
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_VOLTAGE_ERR_MSK     (0x01U << XENSIV_PAS_GAS_A2L_REG_SELF_TEST_VOLTAGE_ERR_POS)
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_TEMP_ERR_POS        (1U)
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_TEMP_ERR_MSK        (0x01U << XENSIV_PAS_GAS_A2L_REG_SELF_TEST_TEMP_ERR_POS)
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_SIMIC_ERR_POS       (2U)
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_SIMIC_ERR_MSK       (0x01U << XENSIV_PAS_GAS_A2L_REG_SELF_TEST_SIMIC_ERR_POS)
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_EMITTER_ERR_POS     (3U)
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_EMITTER_ERR_MSK     (0x01U << XENSIV_PAS_GAS_A2L_REG_SELF_TEST_EMITTER_ERR_POS)
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_ABOC_DRIFT_ERR_POS  (4U)
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_ABOC_DRIFT_ERR_MSK  (0x01U << XENSIV_PAS_GAS_A2L_REG_SELF_TEST_ABOC_DRIFT_ERR_POS)
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_LIFETIME_ERR_POS    (5U)
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_LIFETIME_ERR_MSK    (0x01U << XENSIV_PAS_GAS_A2L_REG_SELF_TEST_LIFETIME_ERR_POS)
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_REPLACE_SEN_POS     (7U)
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_REPLACE_SEN_MSK     (0x01U << XENSIV_PAS_GAS_A2L_REG_SELF_TEST_REPLACE_SEN_POS)

// DENOISE_CFG
#define XENSIV_PAS_GAS_A2L_REG_DENOISE_CFG_SMOOTHING_FACT_POS    (0U)
#define XENSIV_PAS_GAS_A2L_REG_DENOISE_CFG_SMOOTHING_FACT_MSK    (0x3fU << XENSIV_PAS_GAS_A2L_REG_DENOISE_CFG_SMOOTHING_FACT_POS)

// ABOC_CYCLE
#define XENSIV_PAS_GAS_A2L_REG_ABOC_CYCLE_SMOOTHING_FACT_POS     (0U)
#define XENSIV_PAS_GAS_A2L_REG_ABOC_CYCLE_SMOOTHING_FACT_MSK     (0x3fU << XENSIV_PAS_GAS_A2L_REG_ABOC_CYCLE_SMOOTHING_FACT_POS)

// SELF_TEST_CLR
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_CLR_VOLTAGE_ERR_CLR_POS     (0U)
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_CLR_VOLTAGE_ERR_CLR_MSK     (0x01U << XENSIV_PAS_GAS_A2L_REG_SELF_TEST_CLR_VOLTAGE_ERR_CLR_POS)
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_CLR_TEMP_ERR_CLR_POS        (1U)
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_CLR_TEMP_ERR_CLR_MSK        (0x01U << XENSIV_PAS_GAS_A2L_REG_SELF_TEST_CLR_TEMP_ERR_CLR_POS)
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_CLR_SIMIC_ERR_CLR_POS       (2U)
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_CLR_SIMIC_ERR_CLR_MSK       (0x01U << XENSIV_PAS_GAS_A2L_REG_SELF_TEST_CLR_SIMIC_ERR_CLR_POS)
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_CLR_EMITTER_ERR_CLR_POS     (3U)
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_CLR_EMITTER_ERR_CLR_MSK     (0x01U << XENSIV_PAS_GAS_A2L_REG_SELF_TEST_CLR_EMITTER_ERR_CLR_POS)
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_CLR_ABOC_DRIFT_ERR_CLR_POS  (4U)
#define XENSIV_PAS_GAS_A2L_REG_SELF_TEST_CLR_ABOC_DRIFT_ERR_CLR_MSK  (0x01U << XENSIV_PAS_GAS_A2L_REG_SELF_TEST_CLR_ABOC_DRIFT_ERR_CLR_POS)

// ALARM_HYS_H
#define XENSIV_PAS_GAS_A2L_REG_ALARM_HYS_H_POS         (0x0U)
#define XENSIV_PAS_GAS_A2L_REG_ALARM_HYS_H_MASK        (0x7fU << XENSIV_PAS_GAS_A2L_REG_ALARM_HYS_H_POS)

// ALARM_HYS_L
#define XENSIV_PAS_GAS_A2L_REG_ALARM_HYS_L_POS         (0x0U)
#define XENSIV_PAS_GAS_A2L_REG_ALARM_HYS_L_MASK        (0xffU << XENSIV_PAS_GAS_A2L_REG_ALARM_HYS_L_POS)

// ABS_HUM_REF_H
#define XENSIV_PAS_GAS_A2L_REG_ABS_HUM_REF_H_POS       (0x0U)
#define XENSIV_PAS_GAS_A2L_REG_ABS_HUM_REF_H_MASK      (0x03U << XENSIV_PAS_GAS_A2L_REG_ABS_HUM_REF_H_POS)

// ABS_HUM_REF_L
#define XENSIV_PAS_GAS_A2L_REG_ABS_HUM_REF_L_POS       (0x0U)
#define XENSIV_PAS_GAS_A2L_REG_ABS_HUM_REF_L_MASK      (0xffU << XENSIV_PAS_GAS_A2L_REG_ABS_HUM_REF_L_POS)

// HC_CTRL
#define XENSIV_PAS_GAS_A2L_REG_HC_CTRL_ENABLE_POS       (0x0U)
#define XENSIV_PAS_GAS_A2L_REG_HC_CTRL_ENABLE_MASK      (0x0U << XENSIV_PAS_GAS_A2L_REG_HC_CTRL_ENABLE_POS)
#define XENSIV_PAS_GAS_A2L_REG_HC_CTRL_ERR_CLR_POS      (1U)
#define XENSIV_PAS_GAS_A2L_REG_HC_CTRL_ERR_CLR_MASK     (0x0U << XENSIV_PAS_GAS_A2L_REG_HC_CTRL_ERR_CLR_POS)
#define XENSIV_PAS_GAS_A2L_REG_HC_CTRL_HUM_ERR_POS      (2U)
#define XENSIV_PAS_GAS_A2L_REG_HC_CTRL_HUM_ERR_MASK     (0x0U << XENSIV_PAS_GAS_A2L_REG_HC_CTRL_HUM_ERR_POS)
#define XENSIV_PAS_GAS_A2L_REG_HC_CTRL_STALE_HUM_POS    (3U)
#define XENSIV_PAS_GAS_A2L_REG_HC_CTRL_STALE_HUM_MASK   (0x0U << XENSIV_PAS_GAS_A2L_REG_HC_CTRL_STALE_HUM_POS)
#define XENSIV_PAS_GAS_A2L_REG_HC_CTRL_ABS_HUM_POS      (4U)
#define XENSIV_PAS_GAS_A2L_REG_HC_CTRL_ABS_HUM_MASK     (0x0U << XENSIV_PAS_GAS_A2L_REG_HC_CTRL_ABS_HUM_POS)

#endif /* XENSIV_PAS_GAS_A2L_REGS_H_ */
